### ISSUE TITLE
demos not working on chrome Version 37.0.2062.120 Debian jessie/sid (281580) (64-bit)

### ISSUE THREAD

**Issue by makoConstruct** [underscorediscovery/differ#12]
In demo 1 for instance, all I see is
Click to toggle using the polygon, or using the circle. See https://github.com/underscorediscovery/hxcollision for code 

#nme-application is just a blank square. There are no console errors.

**Comment by underscorediscovery** [comment]
The new usage test uses webgl, and will continue to add tests/feature demos.
